version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bigdata_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bigdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
      - ./data:/data_source
    ports:
      - "5432:5432"
    restart: always 

volumes:
  postgres_data:
